# Site settings
name: Khushi Sabarad
title: Khushi Sabarad | Data Engineer, DevOps
description: Software engineer passionate about building and exploring cloud services for data engineering projects.
url: https://khushi-sabarad.github.io/
baseurl: ''
email: khushi.sabarad@gmail.com
cover: https://khushi-sabarad.github.io/img/og.png
logo: https://khushi-sabarad.github.io/img/emojis/technologist.png
resume: https://khushi-sabarad.github.io/resume.pdf
social:
  - title: email
    url: mailto:khushi.sabarad@gmail.com
  - title: github
    url: https://github.com/khushi-sabarad
  - title: linkedin
    url: https://www.linkedin.com/in/khushi-sabarad
  - title: medium
    url: https://medium.com/@khushi.sabarad

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
